version: '3'

tasks:
  clean:
    cmds:
      - ./mill native.cleanNative
      - ./mill clean

  package:
    silent: true
    cmds:
      - ./mill -Dbuild-all-targets=true main.universalStagePackageZip
      - echo ""
      - echo "Generated files:"
      - find ./out/main/universalStagePackageZip.dest -type f
