/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hexacraft_rs_RustLib_PerlinNoise4D */

#ifndef _Included_hexacraft_rs_RustLib_PerlinNoise4D
#define _Included_hexacraft_rs_RustLib_PerlinNoise4D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hexacraft_rs_RustLib_PerlinNoise4D
 * Method:    init
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_hexacraft_rs_RustLib_00024PerlinNoise4D_init
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     hexacraft_rs_RustLib_PerlinNoise4D
 * Method:    noise
 * Signature: (JDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_hexacraft_rs_RustLib_00024PerlinNoise4D_noise
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
