/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hexacraft_rs_RustLib_NoiseGenerator4D */

#ifndef _Included_hexacraft_rs_RustLib_NoiseGenerator4D
#define _Included_hexacraft_rs_RustLib_NoiseGenerator4D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hexacraft_rs_RustLib_NoiseGenerator4D
 * Method:    storePerms
 * Signature: ([I)J
 */
JNIEXPORT jlong JNICALL Java_hexacraft_rs_RustLib_00024NoiseGenerator4D_storePerms
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     hexacraft_rs_RustLib_NoiseGenerator4D
 * Method:    createLayeredNoiseGenerator
 * Signature: ([J)J
 */
JNIEXPORT jlong JNICALL Java_hexacraft_rs_RustLib_00024NoiseGenerator4D_createLayeredNoiseGenerator
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     hexacraft_rs_RustLib_NoiseGenerator4D
 * Method:    genNoise
 * Signature: (JDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_hexacraft_rs_RustLib_00024NoiseGenerator4D_genNoise
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
