/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hexacraft_rs_RustLib__ */

#ifndef _Included_hexacraft_rs_RustLib__
#define _Included_hexacraft_rs_RustLib__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hexacraft_rs_RustLib__
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hexacraft_rs_RustLib_00024_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
