/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hexacraft_rs_RustLib */

#ifndef _Included_hexacraft_rs_RustLib
#define _Included_hexacraft_rs_RustLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hexacraft_rs_RustLib
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hexacraft_rs_RustLib_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
