name: CI

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "openjdk@1.17"
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Run tests
        run: sbt coverage test coverageReport coveralls
        shell: bash
      - name: Clean up cache
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
        shell: bash