name: CI

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Setup
        uses: coursier/setup-action@v1
        with:
          jvm: "adoptium:1.17"
      - name: Run tests
        run: sbt coverage test
        shell: bash
      - name: Coveralls
        run: sbt coverageAggregate coveralls
        shell: bash
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean up cache
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
        shell: bash