name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Setup
        uses: coursier/setup-action@v1
        with:
          jvm: "adoptium:1.17"
      - name: Build
        run: ./mill __.compile
        shell: bash
      - name: Run tests
        run: ./mill __.test
        shell: bash
